### ISSUE TITLE
[BUG]: Application Level access control is not enforced

### ISSUE THREAD

**Issue by dbosco** [privacera/paig#108]
### What Happened?

For GenAI Applications, currently the user and groups level access controls are not enforced

### Application Version

N/A

### Python Version

3.11.3

### Platform Version

Docker

### Steps to Reproduce

1. Go to the GenAI Application
2. Set access policies for the GenAI to any user (change from Everyone)
3. Try invoking the shield with a different user
4. It is expected to deny, but it is allowed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
Issue is resolved.
