### ISSUE TITLE
[TASK]: Release paig-client 0.0.2 version

### ISSUE THREAD

**Issue by SiddheshwarKamble** [privacera/paig#116]
### Task Details

Release paig-client 0.0.2 version to public pypi.
Update `paig-client/CHANGELOG.md` with changes and enhancements.

### Priority Level

- [ ] Low
- [ ] Medium
- [X] High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
paig-client is released.
