### ISSUE TITLE
[ENH]: Support for SecureChat with Cloude Models

### ISSUE THREAD

**Issue by amrakshay** [privacera/paig#128]
### Feature Description

**Objective:**
Enhance the SecureChat functionality by integrating it with Cloude models to generate embeddings and facilitate question-answering capabilities. This integration will improve the security and efficiency of user interactions within the SecureChat environment.

**Key Features:**

1. **Integration with Cloude Models:**
   - Implement support for Cloude models to generate embeddings that can be utilized for processing and understanding user queries in SecureChat.

2. **Embedding Generation:**
   - Enable the generation of high-quality embeddings from user input, allowing for more contextually aware responses.

3. **Enhanced Question-Answering:**
   - Develop a robust mechanism for retrieving answers based on the embeddings generated by the Cloude models.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
@SiddheshwarKamble @amrakshay as the changes are merged, can we plan to test these with Cloude models.

**Comment by pravin-bansod** [comment]
changes are merged and tested against AWS Bedrock "anthropic.claude-3-5-sonnet-20240620-v1:0" model.
