### ISSUE TITLE
[ENH]: Extend AWS Bedrock Guardrail support to take properties from UI

### ISSUE THREAD

**Issue by sushilsani** [privacera/paig#132]
### Contact Details

amrakshay

### Feature Description

In #120 we added support for AWS Bedrock Guardrail by setting the properties.
We need to add / extend support of setting the Guardrail id and version for the application on UI.
Shield Service to check the guardrail id and version from database and make call to AWS Bedrock Guardrail to authorize request. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
Changes are merged.
