### ISSUE TITLE
[BUG]: Public Group Policy Not Applied in Vector Database Filtering

### ISSUE THREAD

**Issue by akshayr-privacera-github** [privacera/paig#55]
### Contact Details

akshay.rahatwal@privacera.com

### What Happened?

When I create a vector database filtering policy and add only the "public" group to the policy, this policy should apply to all users, as the public group implies universal access. However, the policy is not getting applied to users as expected. Any user-based policies or policies for non-public groups are working correctly.

### Application Version

0.0.2

### Python Version

3.11

### Platform Version

macOS 14.3.1

### Steps to Reproduce

1. Create a new vector database filtering policy.
2. Assign only the "public" group to the policy, specifying the desired filter criteria.
3. Attempt to access the vector database with multiple users who should have access based on the public policy.
4. Observe that the filtered data, which should be visible to all users, is not displayed, and instead, all users can see all the data without any filtering.
5. Create and assign another policy to a non-public group or specific users with similar filter criteria.
6. Observe that this policy works as expected, applying the correct filtering for those users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
This has been fixed.
