### ISSUE TITLE
[BUG]: PAIG installation process is encountering an issue with python 3.9

### ISSUE THREAD

**Issue by vinayakbagal** [privacera/paig#82]
### What Happened?

I am attempting to install paig_opensource with Python 3.9.6. However, the installation process is encountering an issue where the botocore library is being installed in multiple versions. As a result, the installation fails with the following error:
`ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

### Application Version

0.0.2

### Python Version

3.9.6

### Platform Version

macOS 14.6.1

### Steps to Reproduce

1. Use python version 3.9.x
2. Install the paig as per the instructions.
3. Observe the botocore library is being installed in multiple versions
4. At then the installation fails with the below error -
`ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

### Relevant Log Output

```shell
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasinght** [comment]
https://docs.paig.ai/developers/paig-server/start-dev-server.html

python >= 3.10 only supported
