### ISSUE TITLE
[ENH]: Improve API Error Handling for Wrong API Endpoints

### ISSUE THREAD

**Issue by vinayakbagal** [privacera/paig#84]
### Feature Description

Currently, when a user hits an incorrect API endpoint, the error response is not as informative as it could be. To improve the developer experience and make debugging easier, we propose enhancing the response for wrong API endpoints as below.

Here's an example of a well-structured response:

Example - GET 'http://localhost:9090/api/group'
Response -
`{
    "timestamp": "2024-09-16T11:21:21.470+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/api/group"
}`

Key components -
1. HTTP Status Code: 404 Not Found – clearly indicating the issue.
2. Path: Showing the invalid endpoint requested.

This helps the client understand the problem and provides them with the information they need to fix the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
Changed are implemented.
