### ISSUE TITLE
[BUG]: Fix URL to Sample Application in Quick Start Page

### ISSUE THREAD

**Issue by dbosco** [privacera/paig#99]
### What Happened?

The current link to the sample application in the Quick Start page https://docs.paig.ai/quick-start/index.html is incorrect. The link https://github.com/privacera/notebooks/tree/main/paig-os needs to be updated to https://github.com/privacera/paig/tree/main/notebooks/paig-os

**Acceptance Criteria:**
1. Ensure the new link points to the correct path: `https://github.com/privacera/paig/tree/main/notebooks/paig-os`.

### Application Version

N/A

### Python Version

N/A

### Platform Version

N/A

### Affected Browsers

Other

### Steps to Reproduce

1. Click https://docs.paig.ai/quick-start/index.html
2. Check for 
> All the Quick Start notebooks and sample applications are also available in the [GitHub repository (https://github.com/privacera/notebooks/tree/main/paig-os)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravin-bansod** [comment]
this has been fixed.
